import Head from "next/head";

import { Inter } from "next/font/google";

import SwipeableCards from "@/components/SwipeableCards";

import { CardData } from "@/types";


const cards: CardData[] = [
  { id: "1", image: "https://picsum.photos/id/688/400/600", text: "ADMIRE" },
  { id: "2", image: "https://picsum.photos/id/898/400/600", text: "ANXIOUS" },
  { id: "3", image: "https://picsum.photos/id/1050/400/600", text: "BORROW" },
  { id: "4", image: "https://picsum.photos/id/901/400/600", text: "CAMPSITE" },
  { id: "5", image: "https://picsum.photos/id/353/400/600", text: "DESPITE" },
  { id: "6", image: "https://picsum.photos/id/419/400/600", text: "EFFICIENT" },
  { id: "7", image: "https://picsum.photos/id/743/400/600", text: "ESSENTIAL" },
  { id: "8", image: "https://picsum.photos/id/859/400/600", text: "EXHAUSTED" },
  { id: "9", image: "https://picsum.photos/id/879/400/600", text: "FERRY" },
  { id: "10", image: "https://picsum.photos/id/184/400/600", text: "RUBBER" },
];

const inter = Inter({ subsets: ["latin"] });

const handleSwipeLeft = () => {
  console.log("Left!")
};

const handleSwipeRight = () => {
  console.log("Right!")
};

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Treng</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto px-4 py-8 h-screen">
        <div className="flex flex-col flex-1">
          <div className="flex-none h-14">
            <h2 className={inter.className}>Treng 😋</h2>
            <p className="text-gray-500">Learn English easy!</p>
          </div>
          <div className="grow h-14">
            <SwipeableCards data={cards} onSwipeLeft={handleSwipeLeft} onSwipeRight={handleSwipeRight}/>
          </div>
        </div>
      </main>
    </>
  );
}
/* <a
            href="/about"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            About us
          </a> */
